name: ge-web
version: '0.1'
summary: Desktop client for Google Earth Web.
description: |
Google Earth Web. 

confinement: strict
grade: stable

parts:
  electron-app:
    plugin: nodejs
    source: app/

    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio

    after:
      - desktop-gtk2

    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules

apps:
 ge-web:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/app/ge-web
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
